### ISSUE TITLE
Total charge of protein  used in DFT calculaions.

### ISSUE THREAD

**Issue by zubatyuk** [Honza-R/PL-REX#1]
Hi. 
Thanks a lot for sharing the dataset. I want to do some benchmark. Please, can you advise how to get total charge for the structures in the `receptor.pdb` files?
- Roman

**Comment by Honza-R** [comment]
I added two tables with the charge of the receptor, one for the PL-REX structures, and one for the smaller (~1000 atoms) model. I don't have charges of the whole proteins at hand now.

The files are at the root level of the repo, I might move these data to a better place later.

**Comment by zubatyuk** [comment]
Thank you!
