### ISSUE TITLE
Parameters for non-standard residues

### ISSUE THREAD

**Issue by jrihon** [Honza-R/PL-REX#2]
The receptor.pdb structures in structures_pl-rex contain non-standard residues (eg BNC, BCC, BNG, ...). Would it please be possible to provide library/forcefield files for these residues to reproduce the optimizations with AMBER?

Thanks in advance!

**Comment by Honza-R** [comment]
I have added the AMBER parameter files for these as the 'ff' directory.

**Comment by jrihon** [comment]
Thank you very much for the help!
