### ISSUE TITLE
the reproduced scores are not the same as those in the dataset

### ISSUE THREAD

**Issue by baogenduan** [Honza-R/PL-REX#3]
Hi,

  Thanks for sharing the dataset.  I want to reproduce the resutls of SQM2.20 for the target (001-CA2). But the obtained values are not the same as those in the dataset.
  
            reproduced   SQM.2.20           
5NXG   -52.044          -46.406
5NXI    -41.322          -37.175
5NXO   -46.664          -47.025
5NXP   -42.577          -44.059
5NXV   -38.235          -41.725
5NXW  -41.911          -40.386

The calculation steps are as follows

1. deltaGconf(L) is the difference of single point energy(sp) calculated at the PM6-D3H4X/COSMO2 level with optimized free ligand and the sepeated ligand from P-L complex

2. detaEint + deltadeltaGsolv = sp(complex, PM6-D3H4X/COSMO2) - sp(receptor, PM6-D3H4X/COSMO2) -sp(ligand, PM6-D3H4X/COSMO2)
  In the course of calculation, the initial structures are from the dataset.

3. TdeltaS. In the reproduced examples, this terms are all zero.

May I ask if the difference in results is due to using the wrong equations in the calulation of each term of SQM.2.20 score.

Thanks in advance!

**Comment by Honza-R** [comment]
First, the SQM2.20 score uses an updated version of the PM6-D3H4X
corrections, as described in the paper. However, the results obtained with
the default PM6-D3H4X are also quite good, the correlation of the scores
obtained with this setup are reported in the paper.

Second, even with the identical methods, the exact value of the scores may
be hard to reproduce as MOPAC calculations are not perfectly reproducible
across different hardware. I'd recommend not evaluating the scores
themselves, but only their correlation with the experimental free energies.

**Comment by baogenduan** [comment]
Thank you for your suggestion.
